---
# tasks file for roles/redis
- name: Install redis
  yum:
    name: redis
    state: latest
- name: Config redis
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    mode: "0640"
    owner: redis
    group: root
  notify: Restart redis
- name: Start redis
  systemd:
    name: redis
    state: started
    enabled: yes
