---
# tasks file for roles/mariadb
- name: Install mariadb-server
  yum:
    name: mariadb-server
    state: latest
- name: Config mariadb-server
  copy:
    src: server.cnf
    dest: /etc/my.cnf.d/server.cnf
    mode: "0644"
    owner: root
    group: root
  notify: Restart mariadb
- name: Start mariadb
  systemd:
    name: mariadb
    state: started
- name: set mysql root password
  shell: /usr/bin/mysqladmin -uroot  password "123456"
  ignore_errors: yes
  run_once: true
